[package]
name = "another-rust-coin"
version = "0.1.0"
authors = ["Quentin Boyer <qbsecond@gmail.com>"]
description = "A rust node implementing the ensicoin protocol"
edition = "2018"

[dependencies]
futures = "^0.1"
ensicoin_serializer = "^2.0.0"
ensicoin_serializer_derive = "^0.2"
tokio = "^0.1"
tokio-timer = "^0.2"
log = "^0.4"
simplelog = "^0.5.0"
clap = "^2.33.0"
ripemd160 = "^0.8.0"
secp256k1 = "^0.12.2"
sled = "^0.23"
dirs = "^1.0.5"
lazy_static = "^1.3.0"
sha2 = "^0.8.0"
generic-array = {version = "^0.13.0", features = ["serde"] }
typenum = "^1.10.0"
prost = "^0.5.0"
bytes = "^0.4.12"
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc", features= ["tower-hyper"] }
tower-hyper = { git = "https://github.com/tower-rs/tower-hyper" }
rustyline = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-serde-json = "0.2"
ensicoin_messages = "^0.3"
num-bigint = "^0.2"
tokio-bus = "^0.1"

[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc", features = ["tower-hyper"] }
